version: '3.4'

services:
  
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data  

#--------------------------------------------------------------------------------------------
  catalogdb:
    container_name: catalog.db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
   
  basketdb:
    container_name: basket.db
    restart: always
    ports:
      - "6379:6379"
   
  discountdb:
    container_name: discount.db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=DiscountDb
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/root/.pgadmin
#--------------------------------------------------------------------------------------------

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSetting:ConnectionString=mongodb://catalog.db:27017"
    depends_on:
      - catalogdb
    ports:
      - "8123:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSetting:ConnectionString=basket.db:6379
      - "GrpcSetting:DiscountUrl=http://discount.grpc"
    depends_on:
      - basketdb
    ports:
      - "8124:80"


  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSetting:ConnectionString=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin;
    ports:
      - "8125:80"
    depends_on:
      - discountdb


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
       - "DatabaseSetting:ConnectionString=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin";
    depends_on:
      - discountdb
    ports:
      - "8126:80"

